import type { PostStatus } from "@ssm/domain";

/**
 * Badge tones resolve to CSS custom properties, so a status chip stays legible in
 * both themes instead of being pinned to a light-mode palette.
 */
type BadgeTone = "neutral" | "success" | "warning" | "danger" | "info" | "accent";

const toneClass: Record<BadgeTone, string> = {
  neutral: "badge",
  success: "badge badge-success",
  warning: "badge badge-warning",
  danger: "badge badge-danger",
  info: "badge badge-info",
  accent: "badge badge-accent"
};

const statusLabels: Record<string, string> = {
  draft: "Draft",
  in_review: "In review",
  revisions_needed: "Needs changes",
  approved: "Approved",
  scheduled: "Scheduled",
  publishing: "Publishing",
  published: "Published",
  failed: "Failed",
  archived: "Archived",
  disabled: "Disabled",
  at_risk: "At risk",
  completed: "Completed",
  todo: "To do",
  in_progress: "In progress",
  blocked: "Blocked",
  done: "Done",
  passed: "Passed",
  flagged: "Flagged",
  rejected: "Rejected",
  resolved: "Resolved",
  low: "Low",
  medium: "Medium",
  high: "High",
  connected: "Connected",
  expired: "Expired",
  revoked: "Revoked",
  error: "Error",
  pending: "Pending",
  consumed: "Consumed",
  active: "Active",
  trusted: "Trusted",
  recommended: "Recommended",
  reserved: "Reserved",
  used: "Used",
  skipped: "Skipped",
  paused: "Paused",
  invited: "Invited",
  suspended: "Suspended",
  accepted: "Accepted",
  ltr: "LTR",
  rtl: "RTL",
  global: "Global",
  us: "US",
  eu: "EU",
  in: "India",
  jp: "Japan",
  warning: "Warning",
  critical: "Critical",
  info: "Info",
  negative: "Negative",
  neutral: "Neutral",
  positive: "Positive",
  mixed: "Mixed",
  delivered: "Delivered",
  sent: "Sent",
  suppressed: "Suppressed",
  generated: "Generated",
  ready: "Ready",
  shared: "Shared",
  queued: "Queued",
  processing: "Processing",
  retrying: "Retrying",
  succeeded: "Succeeded",
  canceled: "Canceled",
  virus_scanning: "Virus scan",
  format_detecting: "Detecting",
  optimizing: "Optimizing",
  thumbnailing: "Thumbnailing",
  ai_tagging: "AI tagging",
  storing: "Storing",
  cdn_distributing: "CDN"
};

const statusTones: Record<string, BadgeTone> = {
  draft: "neutral",
  in_review: "warning",
  revisions_needed: "danger",
  approved: "success",
  scheduled: "accent",
  publishing: "info",
  published: "success",
  failed: "danger",
  archived: "neutral",
  disabled: "neutral",
  at_risk: "warning",
  completed: "success",
  todo: "neutral",
  in_progress: "info",
  blocked: "danger",
  done: "success",
  passed: "success",
  flagged: "warning",
  rejected: "danger",
  resolved: "neutral",
  low: "success",
  medium: "warning",
  high: "danger",
  connected: "success",
  expired: "warning",
  revoked: "danger",
  error: "danger",
  pending: "warning",
  consumed: "success",
  active: "success",
  trusted: "success",
  recommended: "info",
  reserved: "accent",
  used: "success",
  skipped: "neutral",
  paused: "warning",
  invited: "warning",
  suspended: "danger",
  accepted: "success",
  ltr: "neutral",
  rtl: "accent",
  global: "info",
  us: "info",
  eu: "accent",
  in: "accent",
  jp: "warning",
  warning: "warning",
  critical: "danger",
  info: "info",
  negative: "danger",
  neutral: "neutral",
  positive: "success",
  mixed: "warning",
  delivered: "success",
  sent: "success",
  suppressed: "neutral",
  generated: "success",
  ready: "success",
  shared: "info",
  queued: "accent",
  processing: "info",
  retrying: "warning",
  succeeded: "success",
  canceled: "neutral",
  virus_scanning: "info",
  format_detecting: "info",
  optimizing: "accent",
  thumbnailing: "accent",
  ai_tagging: "accent",
  storing: "warning",
  cdn_distributing: "warning"
};

export function StatusBadge({ status }: { status: PostStatus | string }) {
  const tone = statusTones[status] ?? "neutral";

  return (
    <span className={toneClass[tone]}>{statusLabels[status] ?? status.replace(/_/g, " ")}</span>
  );
}
